services:
  app:
    build: .
    volumes:
      - ./my-project:/var/www/html
    ports:
      - 8080:8080
    environment:
      SS_DATABASE_CLASS: MySQLDatabase
      SS_DATABASE_SERVER: db
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: password
      SS_DATABASE_NAME: silverstripe
      SS_ENVIRONMENT_TYPE: dev

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: silverstripe
      MYSQL_ROOT_PASSWORD: password

